choco install firefox --yes
choco install discord --yes
choco install steam --yes
choco install nodejs-lts --yes
choco install vscode --yes
choco install git --yes
choco install qbittorrent --yes
choco install onlyoffice --yes
choco install tutanota --yes
choco install intellijidea-community --yes
choco install google-chrome-x64 --yes
choco install 7zip --yes
choco install powershell-core --yes
choco install lightshot --yes
